Feature: Church edition
netwerk-digitaal-erfgoed/heritageflix pull request #14
Opened 2022-12-15 13:11 UTC by aabelmann

Do not merge

2022-12-16 09:27 UTC, rmnilsen commented on components/Atoms/Property.vue
> +  }
Waarom moet dit in een trycatch? Is dit URL validatie? Dan misschien handiger om een prop validator toe te voegen

2022-12-16 09:43 UTC, rmnilsen commented on stores/artworks.ts
> +    const topLevelProps = ['heritageObject', 'name', 'identifier', 'description', 'imageContentUrl'];
Deze 2 arrays kunnen gewoon samengevoegd worden lijkt mij.

2022-12-16 09:48 UTC, rmnilsen commented on components/Atoms/Property.vue
> +  }
Inmiddels besproken en daaruit blijkt dat de trycatch toch nodig is omdat de template moet weten of het een link is of niet

2022-12-16 09:48 UTC, rmnilsen requested changes
1 opmerking toegevoegd

2022-12-19 07:38 UTC, aabelmann commented on stores/artworks.ts
> +    const topLevelProps = ['heritageObject', 'name', 'identifier', 'description', 'imageContentUrl'];
Ja kan ik samenvoegen maar zo is het wel duidelijker welke properies namespaces zijn en welke props zijn die we al gebruiken.

2022-12-19 10:50 UTC, rmnilsen commented on stores/artworks.ts
> +    const topLevelProps = ['heritageObject', 'name', 'identifier', 'description', 'imageContentUrl'];
Ja ok. Laat zo maar staan dan

2022-12-19 10:50 UTC, rmnilsen approved these changes

2022-12-20 16:04 UTC, closed without merging